# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identitas',
            old_name='Urut',
            new_name='SKS',
        ),
    ]
