# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20160202_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitas',
            name='NIM',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='identitas',
            name='SKS',
            field=models.CharField(max_length=200),
        ),
    ]
